- id: '1667935594434'
  alias: 01 - Lock Logging
  description: ''
  trigger:
  - platform: event
    event_type: keymaster_lock_state_changed
    event_data:
      state: unlocked
    variables:
      sn: "{%- if trigger.event.data.code_slot_name == \"\" -%}\n  Manual\n{%- else
        -%}\n  {{ trigger.event.data.code_slot_name }}\n{%- endif -%}"
      verb: "{%- if trigger.event.data.code_slot_name == \"\" -%}\n  unlock of\n{%-
        else -%}\n  unlocked\n{%- endif -%}"
  condition: []
  action:
  - service: logbook.log
    data:
      name: '{{ trigger.event.data.lockname }}'
      entity_id: '{{ trigger.event.data.entity_id }}'
      message: '{{ sn }} {{ verb }} the {{ trigger.event.data.lockname }}'
  mode: single
- id: '1669752279062'
  alias: Upstairs Bath Humidity Fan On
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: 6f8c59c23ca8ccbbc9daafb869ce8634
    entity_id: sensor.4_in_1_sensor_humidity
    domain: sensor
    above: 60
  condition: []
  action:
  - type: turn_on
    device_id: 89beaa54fc4d4b3bcf5c486285e6d70a
    entity_id: switch.z_wave_plus_700_series_on_off_switch_2
    domain: switch
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.upstairs_bath_fan_auto
  mode: single
- id: '1669752452638'
  alias: Upstairs Bath Humidity Fan Off
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: 6f8c59c23ca8ccbbc9daafb869ce8634
    entity_id: sensor.4_in_1_sensor_humidity
    domain: sensor
    below: 55
  condition:
  - condition: state
    entity_id: input_boolean.upstairs_bath_fan_auto
    state: 'on'
  action:
  - type: turn_off
    device_id: 89beaa54fc4d4b3bcf5c486285e6d70a
    entity_id: switch.z_wave_plus_700_series_on_off_switch_2
    domain: switch
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.upstairs_bath_fan_auto
  mode: single
- id: '1670102313702'
  alias: Plant Room Grow Lights On
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 39d4166335c404a445b78de6b083795b
    entity_id: switch.z_wave_plus_power_strip_ver_2_0
    domain: switch
  mode: single
- id: '1670102386591'
  alias: Plant Room Grow Lights Off
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 39d4166335c404a445b78de6b083795b
    entity_id: switch.z_wave_plus_power_strip_ver_2_0
    domain: switch
  mode: single
- id: '1670514295590'
  alias: Upstairs Bathroom Light Off - Open Door
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: f192fba261a43fd1aeb34932dd88d8c7
    entity_id: binary_sensor.open_close_xs_sensor_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: 0a1faa1fdd0076f289dc08ef4872af56
    entity_id: switch.z_wave_plus_700_series_on_off_switch
    domain: switch
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: timer.cancel
    data: {}
    target:
      entity_id: timer.upstairs_bathroom_light_timer
  - type: turn_off
    device_id: 0a1faa1fdd0076f289dc08ef4872af56
    entity_id: switch.z_wave_plus_700_series_on_off_switch
    domain: switch
  mode: single
- id: '1671289220672'
  alias: Tag Office Desk is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 2f7b0f63-68e0-4dc1-8b30-7dc0bea8899e
  condition: []
  action:
  - type: turn_on
    device_id: 753645fa137551dd5fd879ce68076ec0
    entity_id: light.z_wave_plus_700_series_dimmer_switch
    domain: light
    brightness_pct: 40
  mode: single
- id: '1671304036359'
  alias: Upstairs Bathroom Light Timer - Light On
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 0a1faa1fdd0076f289dc08ef4872af56
    entity_id: switch.z_wave_plus_700_series_on_off_switch
    domain: switch
  condition:
  - type: is_open
    condition: device
    device_id: f192fba261a43fd1aeb34932dd88d8c7
    entity_id: binary_sensor.open_close_xs_sensor_window_door_is_open
    domain: binary_sensor
  action:
  - service: timer.start
    data: {}
    target:
      entity_id: timer.upstairs_bathroom_light_timer
  mode: single
- id: '1671304471870'
  alias: Upstairs Bathroom Light Timer Finished
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.upstairs_bathroom_light_timer
  condition: []
  action:
  - type: turn_off
    device_id: 0a1faa1fdd0076f289dc08ef4872af56
    entity_id: switch.z_wave_plus_700_series_on_off_switch
    domain: switch
  mode: single
- id: '1671304829027'
  alias: Upstairs Bath Timer Pause
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: f192fba261a43fd1aeb34932dd88d8c7
    entity_id: binary_sensor.open_close_xs_sensor_window_door_is_open
    domain: binary_sensor
  condition: []
  action:
  - service: timer.pause
    data: {}
    target:
      entity_id: timer.upstairs_bathroom_light_timer
  mode: single
- id: '1671410819497'
  alias: 'Upstairs Bath Cancel Timer '
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 0a1faa1fdd0076f289dc08ef4872af56
    entity_id: switch.z_wave_plus_700_series_on_off_switch
    domain: switch
  condition:
  - condition: state
    entity_id: timer.upstairs_bathroom_light_timer
    state: active
  action:
  - service: timer.cancel
    data: {}
    target:
      entity_id: timer.upstairs_bathroom_light_timer
  mode: single
